#! /bin/sh
### BEGIN INIT INFO
# Provides:          redis-server
# Required-Start:    $network $named $remote_fs $syslog
# Required-Stop:     $network $named $remote_fs $syslog
# Default-Start:     2 3 4 5                                                                                                                               
# Default-Stop:      0 1 6                                                                                                                                 
### END INIT INFO                 

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=`which redis-server`
REDIS_CLI=`which redis-cli`
CONFIG_FILE="/etc/redis/redis.conf"
DAEMON_ARGS="$CONFIG_FILE" 
DESC="Redis server"
LISTENING_PORT=6379

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

if [ ! -d /var/run/redis ]; then
        mkdir -p /var/run/redis
fi

chown redis:redis /var/run/redis

start_redis() {
        start-stop-daemon --start  --quiet --chuid redis:redis --pidfile /var/run/redis/redis.pid \
                --exec $DAEMON -- $DAEMON_ARGS
}

stop_redis() {
        $REDIS_CLI -p $LISTENING_PORT SHUTDOWN
}

status_redis() {
        status_of_proc -p "/var/run/redis/redis.pid" "${DAEMON}" "${NAME}"
}

case "$1" in
    start)
  log_begin_msg "Starting $DESC"
  start_redis
  log_end_msg $?
  ;;
    stop)
  log_begin_msg "Stopping $DESC"
  stop_redis
  log_end_msg $?
  ;;
    status)
      status_redis
        ;;
    restart|force-reload)
  log_begin_msg "Restarting $DESC"
  stop_redis
  sleep 1
  start_redis
  log_end_msg $?
  ;;
    *)
  echo "Usage: $0 {start|stop|status|restart}" >&2
  exit 1
  ;;
esac
